<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsTableSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            ['id' => 1, 'name' => 'Pánske bavlnené tričko', 'description' => 'Klasické pánske tričko z kvalitnej 100% bavlny, ktoré poskytuje maximálne pohodlie počas celého dňa. Je ideálne na bežné nosenie, do práce aj na voľný čas. Vďaka jednoduchému dizajnu sa ľahko kombinuje s džínsami, kraťasmi či mikinou. Dostupné v rôznych farebných variantoch a veľkostiach.', 'producerinfo' => 'XYZ Odevy', 'price' => 19.99, 'productinfo' => '100 % bavlna, gramáž 180 g/m², regular fit, krátke rukávy, okrúhly výstrih, pranie pri 40 °C', 'stockquantity' => 50],
            ['id' => 2, 'name' => 'Pánske úzke džínsy', 'description' => 'Moderné pánske úzke džínsy so štýlovým strihom, ktorý perfektne sedí. Vyrobené z pružného denimu, ktorý zabezpečuje pohodlie pri nosení počas celého dňa. Vhodné na každodenné nosenie aj výnimočné príležitosti. Kombinovateľné s tričkami, košeľami aj sakom.', 'producerinfo' => 'DenimWorks', 'price' => 39.99, 'productinfo' => '98 % bavlna, 2 % elastan, slim fit, zips a gombík, 5 vreciek, stredný pás, pranie pri 30 °C', 'stockquantity' => 30],
            ['id' => 3, 'name' => 'Dámske letné šaty', 'description' => 'Ľahké a vzdušné letné šaty s romantickým strihom, ideálne na horúce dni. Vyrobené z jemného a príjemného materiálu, ktorý umožňuje pokožke dýchať. Vďaka ženskému dizajnu a pohodlnému strihu sú vhodné na pláž, do mesta aj na večernú prechádzku.', 'producerinfo' => 'MódnyTrend', 'price' => 49.99, 'productinfo' => '100 % viskóza, dĺžka po kolená, bez rukávov, V-výstrih, bez zapínania, ručné pranie odporúčané', 'stockquantity' => 20],
            ['id' => 4, 'name' => 'Detské hračkárske auto', 'description' => 'Farebné hračkárske auto pre deti od 3 rokov, ktoré podporuje rozvoj motoriky a predstavivosti. Odolné plastové prevedenie zabezpečuje dlhú životnosť aj pri častom používaní. Vhodné na hru doma aj vonku. Skvelý darček pre malých nadšencov áut.', 'producerinfo' => 'Hračkárstvo', 'price' => 15.99, 'productinfo' => 'Plast ABS, rozmery 20 × 10 × 8 cm, vhodné od 3 rokov, spätný pohon, certifikácia CE, bez BPA', 'stockquantity' => 100],
            ['id' => 5, 'name' => 'Bežecké topánky', 'description' => 'Ľahké a priedušné bežecké topánky navrhnuté pre maximálne pohodlie a výkon. Podrážka tlmí nárazy a zabezpečuje dobrú priľnavosť na rôznych povrchoch. Ideálne pre krátke aj dlhé trate. Podporujú správny došľap a znižujú riziko únavy a zranení.', 'producerinfo' => 'ŠportTech', 'price' => 79.99, 'productinfo' => 'Sieťovina a syntetika, EVA medzipodrážka, gumová podrážka, klasické šnurovanie, cca 280 g (veľ. 42)', 'stockquantity' => 25],
            ['id' => 6, 'name' => 'Športová fľaša', 'description' => 'Praktická športová fľaša s objemom 750ml vyrobená z odolného, BPA-free plastu. Uzáver s náustkom umožňuje pohodlné pitie aj počas pohybu. Vhodná do fitka, na bicykel či turistiku. Ľahko sa čistí a je opakovane použiteľná.', 'producerinfo' => 'HydroVybavenie', 'price' => 9.99, 'productinfo' => 'BPA-free plast, objem 750 ml, skrutkovacie viečko, vhodná do umývačky, teplotná odolnosť -10 °C až 60 °C', 'stockquantity' => 60],
            ['id' => 7, 'name' => 'Baseball rukavica', 'description' => 'Kvalitná baseballová rukavica z mäkkej syntetickej kože pre rýchle chytanie loptičiek. Ergonomický tvar umožňuje pohodlný úchop a kontrolu. Vhodná pre začiatočníkov aj pokročilých hráčov. Ideálna na tréning aj rekreačnú hru.', 'producerinfo' => 'Wilson', 'price' => 59.99, 'productinfo' => 'Prírodná koža, veľkosť 12”, pre pravú ruku, mäkká podšívka, pre juniorov a dospelých', 'stockquantity' => 10],
            ['id' => 8, 'name' => 'Bunda', 'description' => 'Univerzálna bunda vhodná na prechodné obdobie. Odolná voči vetru a miernemu dažďu, s vnútornou podšívkou pre príjemné teplo. Moderný strih a praktické vrecká robia z bundy skvelý doplnok do každodenného outfitu. Dostupná v rôznych veľkostiach.', 'producerinfo' => 'North Face', 'price' => 79.99, 'productinfo' => '100 % polyester, syntetická výplň 200 g/m², odnímateľná kapucňa, vodeodolnosť 5000 mm, 3 vrecká', 'stockquantity' => 15],
            ['id' => 9, 'name' => 'Golfová lopta', 'description' => 'Golfová lopta so zvýšenou odolnosťou a optimalizovanou aerodynamikou pre dlhší a stabilnejší let. Vhodná pre hráčov všetkých úrovní. Povrch s viacnásobnými jamkami znižuje odpor vzduchu a zvyšuje presnosť úderov.', 'producerinfo' => 'Titleist', 'price' => 9.99, 'productinfo' => 'Dvojvrstvové jadro, surlyn povrch, priemer 42.67 mm, hmotnosť 45.93 g, kompresia 70', 'stockquantity' => 50],
            ['id' => 10, 'name' => 'Jednoručky', 'description' => 'Set jednoručných činiek s pogumovaným povrchom pre bezpečný úchop. Ideálne na posilňovanie rúk, ramien a hornej časti tela. Dostupné v rôznych hmotnostiach. Vhodné na domáce aj profesionálne cvičenie.', 'producerinfo' => 'GymBeam', 'price' => 19.99, 'productinfo' => '5 kg oceľ, vinylový poťah, protišmykový úchop, šesťhranný tvar, predaj ako pár', 'stockquantity' => 20],
            ['id' => 11, 'name' => 'Mikina', 'description' => 'Pohodlná mikina z mäkkého a hrejivého materiálu, vhodná na každodenné nosenie. Má praktickú kapucňu a predné klokanie vrecko. Ideálna na voľný čas, šport aj chladnejšie dni. Dostupná vo viacerých farbách.', 'producerinfo' => 'Adidas', 'price' => 49.99, 'productinfo' => '80 % bavlna, 20 % polyester, klokanie vrecko, kapucňa so šnúrkou, bez zipsu, gramáž 280 g/m²', 'stockquantity' => 25],
            ['id' => 12, 'name' => 'Tenisky', 'description' => 'Štýlové tenisky s moderným dizajnom a mäkkou podrážkou pre maximálne pohodlie. Vhodné na každodenné nosenie do mesta, školy či práce. Kombinujú komfort a mestský štýl. Dostupné v pánskych aj dámskych veľkostiach.', 'producerinfo' => 'Nike', 'price' => 59.99, 'productinfo' => 'Syntetika a textil, gumová podrážka, textilná stielka, klasické šnurovanie, cca 320 g (veľ. 42)', 'stockquantity' => 30],
            ['id' => 13, 'name' => 'Basketbalová lopta', 'description' => 'Odolná basketbalová lopta s protišmykovým povrchom pre lepší úchop. Vhodná na hru v hale aj na vonkajšom ihrisku. Kvalitné spracovanie zabezpečuje dobrý odraz a dlhú životnosť. Ideálna pre amatérskych aj pokročilých hráčov.', 'producerinfo' => 'Spalding', 'price' => 40.00, 'productinfo' => 'Syntetická koža, veľkosť 7, obvod 75 cm, hmotnosť cca 600 g, vhodná na von aj dnu', 'stockquantity' => 15],
            ['id' => 14, 'name' => 'Turistický batoh', 'description' => 'Funkčný turistický batoh s objemom 30L, ideálny na jednodňové výlety. Disponuje nastaviteľnými popruhmi, priedušným chrbtovým systémom a viacerými priehradkami. Vyrobený z odolného materiálu, ktorý ochráni vaše veci aj v nepriaznivom počasí.', 'producerinfo' => 'Osprey', 'price' => 49.99, 'productinfo' => 'Objem 35 l, nepremokavý nylon, 4 priehradky + sieťky, vystužené popruhy, hrudný pás, držiak na palice', 'stockquantity' => 8],
            ['id' => 15, 'name' => 'Futbalové kopačky', 'description' => 'Futbalové kopačky s ľahkým zvrškom a protišmykovou podrážkou pre optimálnu trakciu na trávnatom povrchu. Dizajn podporuje presné prihrávky a kontrolu lopty. Vhodné pre rekreačných aj súťažných hráčov.', 'producerinfo' => 'Nike', 'price' => 89.99, 'productinfo' => 'Syntetická koža, lisované kolíky FG, šnurovanie, cca 250 g, vnútorné vystuženie', 'stockquantity' => 5],
            ['id' => 16, 'name' => 'Kolieskové korčule', 'description' => 'Kolieskové korčule s kvalitnými ložiskami a nastaviteľnou veľkosťou pre pohodlné jazdenie. Pevná konštrukcia a bezpečnostné zapínanie zabezpečujú stabilitu. Ideálne na rekreačné korčuľovanie v meste alebo v parku.', 'producerinfo' => 'Rollerblade', 'price' => 59.99, 'productinfo' => 'In-line korčule, hliníkový rám, kolieska 82A PU 76 mm, ložiská ABEC-7, šnúrky + pracka + suchý zips', 'stockquantity' => 12],
            ['id' => 17, 'name' => 'Tenisová raketa', 'description' => 'Ľahká tenisová raketa s vyváženým rozložením hmotnosti pre výbornú kontrolu a silu úderu. Vhodná pre začiatočníkov aj mierne pokročilých hráčov. Ergonomická rukoväť zabezpečuje pohodlné držanie počas hry.', 'producerinfo' => 'Wilson', 'price' => 79.99, 'productinfo' => 'Grafitový rám, dĺžka 68.5 cm, veľkosť hlavy 645 cm², hmotnosť 300 g, vyváženie na stred', 'stockquantity' => 7],
            ['id' => 18, 'name' => 'Bežecké tenisky', 'description' => 'Vysokovýkonné bežecké tenisky navrhnuté pre dlhé trate. Ponúkajú výborné tlmenie nárazov, priedušný zvršok a ľahkú konštrukciu. Ideálne pre cestný aj trailový beh. Podporujú prirodzený pohyb chodidla.', 'producerinfo' => 'Adidas', 'price' => 59.99, 'productinfo' => 'Priedušná sieťovina, Phylon pena, gumová podrážka, drop 8 mm, cca 270 g', 'stockquantity' => 9],
            ['id' => 20, 'name' => 'Fitness kruh', 'description' => 'Fitness kruh pre spevnenie brušných svalov a zlepšenie koordinácie. Ergonomický dizajn s protišmykovým povrchom. Vhodný na domáce tréningy, spaľovanie tukov a zábavné cvičenie. Jednoduché zloženie.', 'producerinfo' => 'Crivit', 'price' => 25.99, 'productinfo' => 'Tvrdený plast, penové úchopy, priemer 38 cm, odpor do 25 kg, určené na pilates a spevňovanie', 'stockquantity' => 5],
            ['id' => 21, 'name' => 'Cvičiaci blok', 'description' => 'Ľahký a pevný fitness blok ideálny na jogu, pilates a balančné cvičenia. Podporuje správne držanie tela a pomáha pri výkone náročnejších pozícií. Vyrobený z odolnej peny, poskytuje stabilnú oporu. Vhodný pre začiatočníkov aj pokročilých.', 'producerinfo' => 'Crivit', 'price' => 10.99, 'productinfo' => 'EVA pena, rozmery 30 × 20 × 5 cm, hustota 35 kg/m³, protišmykový povrch, rôzne farby', 'stockquantity' => 10],
        ];

        foreach ($products as $product) {
            $createdAt = Carbon::now()->subDays(rand(1, 365));
            $product['created_at'] = $createdAt;
            $product['updated_at'] = $createdAt->addDays(rand(0, 30));

            DB::table('products')->updateOrInsert(['id' => $product['id']], $product);
        }
    }
}
